# Generated by Django 6.0 on 2025-12-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
    ]
