# Generated by Django 6.0 on 2025-12-14 18:36

import betterhome.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhome', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('role_category', models.CharField(choices=[('founder', 'Founder'), ('director', 'Director'), ('manager', 'Manager'), ('coordinator', 'Coordinator'), ('volunteer', 'Volunteer Coordinator'), ('officer', 'Program Officer'), ('admin', 'Administrator'), ('advisor', 'Advisor'), ('board', 'Board Member')], default='volunteer', help_text='Select role category', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Required for age verification', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('national_id', models.CharField(blank=True, help_text='Required for members 18 years and above. Must be unique.', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('national_id_verified', models.BooleanField(default=False, help_text='Check if national ID has been verified')),
                ('photo', models.ImageField(help_text='Recommended: Square image (500x500px)', upload_to=betterhome.models.team_photo_path)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Display on homepage team section')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TeamDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class (e.g., 'bi-people')", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='departments', to='betterhome.teammember')),
            ],
            options={
                'verbose_name': 'Team Department',
                'verbose_name_plural': 'Team Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
